// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.github.zshine.demo.grpc.lib.proto.helloworld;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.zshine.demo.grpc.proto.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
