// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.github.zshine.demo.grpc.lib.proto.helloworld;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.zshine.demo.grpc.proto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
